--oracle单实例改IP
1、修改主机的/etc/hosts
[oracle@emperor admin]$ more /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6


10.111.40.21 emperor

2、查看$ORACLE_HOME
[oracle@emperor ~]$ cd $ORACLE_HOME
[oracle@emperor db_1]$ cd network/admin/
[oracle@emperor admin]$ more listener.ora
# listener.ora Network Configuration File: /u01/app/oracle/product/11.2.0/db_1/network/admin/listener.ora
# Generated by Oracle configuration tools.

LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 10.111.40.21)(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )

ADR_BASE_LISTENER = /u01/app/oracle

3、如果有TNS，查看TNS文件。
4、登入sqlplus
[oracle@emperor admin]$ sqlplus / as sysdba
alter system register;
5、修改local_listerner
SQL> show parameter listener

NAME                                 TYPE        VALUE
------------------------------------ ----------- ------------------------------
listener_networks                    string
local_listener                       string      (ADDRESS = (PROTOCOL = TCP)(HO
                                                 ST = 10.111.40.21)(PORT = 1521
                                                 ))
remote_listener                      string

SQL> alter system set local_listener='(ADDRESS = (PROTOCOL = TCP)(HOST = 10.111.40.21)(PORT = 1521))';

6、重启监听