CREATE OR REPLACE PROCEDURE SP_TABLE AS
  V_SQL VARCHAR2(30000);
  V_INT INT;
BEGIN
  V_INT := 0;
  FOR V_LOOP IN (SELECT T.OWNER, T.TABLE_NAME FROM SP_TABLE_JLS T) LOOP
    V_SQL := 'SELECT  /*+parallel 2*/  COUNT(1) FROM ' || V_LOOP.OWNER || '.' ||
             V_LOOP.TABLE_NAME || ' where trunc(lrrq)=DATE''2017-10-15''';
    BEGIN
      EXECUTE IMMEDIATE V_SQL
        INTO V_INT;
    EXCEPTION
      WHEN OTHERS THEN
         V_INT := 0;
    END;
    UPDATE SP_TABLE_JLS T
       SET T.JLS = V_INT
     WHERE T.OWNER = V_LOOP.OWNER
       AND T.TABLE_NAME = V_LOOP.TABLE_NAME;
    COMMIT;
  END LOOP;

EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(V_SQL || SQLCODE || SQLERRM);
  
END SP_TABLE;