--Êý¾Ý×ÖµäÓï¾ä
SELECT B.COLUMN_ID,
       A.OWNER,
       A.TABLE_NAME,
       A.COMMENTS,
       B.COLUMN_NAME,
       C.COMMENTS,
       B.DATA_TYPE,
       B.DATA_LENGTH,
       B.DATA_PRECISION,
       B.DATA_SCALE,
       B.NULLABLE
  FROM ALL_TAB_COMMENTS A
  LEFT JOIN ALL_TAB_COLS B
    ON A.OWNER = B.OWNER
   AND A.TABLE_NAME = B.TABLE_NAME
  LEFT JOIN ALL_COL_COMMENTS C
    ON B.OWNER = C.OWNER
   AND B.TABLE_NAME = C.TABLE_NAME
   AND B.COLUMN_NAME = C.COLUMN_NAME
 WHERE A.OWNER LIKE 'HTJS'
 ORDER BY A.OWNER, A.TABLE_NAME, B.COLUMN_ID;
 
SELECT * FROM ALL_TAB_COMMENTS WHERE OWNER like 'HTJS' order by owner,TABLE_NAME
